name: cti-python-stix2 release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
    - name: Install and update essential dependencies
      run: |
        pip install -U pip setuptools
        pip install tox-gh-actions
        pip install codecov
    - name: Test with Tox
      run: |
        tox
    - name: Upload coverage information to Codecov
      uses: codecov/codecov-action@v4.2.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true
    - name: Upload package artifact
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

  publish-to-pypi:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write

    steps:
    - name: Download dist files
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
         skip-existing: true
